### ISSUE TITLE
想问下 快速滑动和慢滑动那个线条的粗细不一样这个是怎么实现的

### ISSUE THREAD

**Issue by MeAndRhythm** [wanglin2/tiny_whiteboard#1]
想问下 快速滑动和慢滑动那个线条的粗细不一样这个是怎么实现的

**Comment by wanglin2** [comment]
根据鼠标滑动的速度来设置线条粗细，可以参考这个代码：https://github.com/wanglin2/tiny_whiteboard/blob/main/tiny-whiteboard/src/utils/index.js#L306
