### ISSUE TITLE
功能请求：能够设置默认绘制的颜色

### ISSUE THREAD

**Issue by whl1207** [wanglin2/tiny_whiteboard#14]
想实现不同主题下，默认绘制颜色的自适应，没有发现配置的位置

**Comment by wanglin2** [comment]
已支持：https://github.com/wanglin2/tiny_whiteboard#%E8%A1%A8%E6%A0%BC1-1-%E7%94%BB%E5%B8%83%E7%8A%B6%E6%80%81%E5%AF%B9%E8%B1%A1state%E7%9A%84%E5%B1%9E%E6%80%A7
