### ISSUE TITLE
这个地方传参错了

### ISSUE THREAD

**Issue by abigmiu** [wanglin2/tiny_whiteboard#3]
https://github.com/wanglin2/tiny_whiteboard/blob/dfe150149aab1b8294af71581b1bec7e85c991eb/tiny-whiteboard/src/Selection.js#L42

![image](https://user-images.githubusercontent.com/43983920/167060348-1301b349-31d6-4dd8-81a1-1f960b734434.png)

**Comment by wanglin2** [comment]
已修复~
